name: Deploy AWS Glue Jobs

on:
  push:
    branches:
      - main  # Runs the workflow when code is pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync Glue Jobs to S3
      run: |
        aws s3 sync glue-jobs s3://nct-glue-jobs/glue-jobs --delete

    - name: Update AWS Glue Jobs
      run: |
        aws glue update-job --job-name T1 --job-update '{"Command": {"ScriptLocation": "s3://nct-glue-jobs/glue-jobs/job_t1/script.py"}}'
        aws glue update-job --job-name T2 --job-update '{"Command": {"ScriptLocation": "s3://nct-glue-jobs/glue-jobs/job_t2/script.py"}}'
